
package com.yonyou.weixin.core.mp.client;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.0.2
 * 2014-12-04T17:57:43.916+08:00
 * Generated source version: 3.0.2
 */

@WebFault(name = "Exception", targetNamespace = "http://itf.mp.uap.yonyou.com/")
public class Exception_Exception extends java.lang.Exception {
    
    private com.yonyou.weixin.core.mp.client.Exception exception;

    public Exception_Exception() {
        super();
    }
    
    public Exception_Exception(String message) {
        super(message);
    }
    
    public Exception_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public Exception_Exception(String message, com.yonyou.weixin.core.mp.client.Exception exception) {
        super(message);
        this.exception = exception;
    }

    public Exception_Exception(String message, com.yonyou.weixin.core.mp.client.Exception exception, Throwable cause) {
        super(message, cause);
        this.exception = exception;
    }

    public com.yonyou.weixin.core.mp.client.Exception getFaultInfo() {
        return this.exception;
    }
}
