
package com.yonyou.weixin.core.mp.client;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 3.0.2
 * 2014-12-04T17:57:43.957+08:00
 * Generated source version: 3.0.2
 * 
 */
 
public class IMPMsgPubQryService_MPMsgPubQryServiceImplPort_Server{

    protected IMPMsgPubQryService_MPMsgPubQryServiceImplPort_Server() throws java.lang.Exception {
        System.out.println("Starting Server");
        Object implementor = new MPMsgPubQryServiceImplPortImpl();
        String address = "http://223.203.195.180:88/ws/iMPMsgPubQryService";
        Endpoint.publish(address, implementor);
    }
    
    public static void main(String args[]) throws java.lang.Exception { 
        new IMPMsgPubQryService_MPMsgPubQryServiceImplPort_Server();
        System.out.println("Server ready..."); 
        
        Thread.sleep(5 * 60 * 1000); 
        System.out.println("Server exiting");
        System.exit(0);
    }
}
