package com.yonyou.weixin.core.mp.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.0.2
 * 2014-12-04T17:57:43.957+08:00
 * Generated source version: 3.0.2
 * 
 */
@WebServiceClient(name = "iMPMsgPubQryService", 
                  wsdlLocation = "http://223.203.195.180:88/ws/iMPMsgPubQryService?wsdl",
                  targetNamespace = "http://impl.mp.uap.yonyou.com/") 
public class IMPMsgPubQryService_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://impl.mp.uap.yonyou.com/", "iMPMsgPubQryService");
    public final static QName MPMsgPubQryServiceImplPort = new QName("http://impl.mp.uap.yonyou.com/", "MPMsgPubQryServiceImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://223.203.195.180:88/ws/iMPMsgPubQryService?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(IMPMsgPubQryService_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://223.203.195.180:88/ws/iMPMsgPubQryService?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public IMPMsgPubQryService_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public IMPMsgPubQryService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public IMPMsgPubQryService_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public IMPMsgPubQryService_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public IMPMsgPubQryService_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public IMPMsgPubQryService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    

    /**
     *
     * @return
     *     returns IMPMsgPubQryService
     */
    @WebEndpoint(name = "MPMsgPubQryServiceImplPort")
    public IMPMsgPubQryService getMPMsgPubQryServiceImplPort() {
        return super.getPort(MPMsgPubQryServiceImplPort, IMPMsgPubQryService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IMPMsgPubQryService
     */
    @WebEndpoint(name = "MPMsgPubQryServiceImplPort")
    public IMPMsgPubQryService getMPMsgPubQryServiceImplPort(WebServiceFeature... features) {
        return super.getPort(MPMsgPubQryServiceImplPort, IMPMsgPubQryService.class, features);
    }

}
