
package com.yonyou.weixin.core.mp.client;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.Date;
import java.util.List;

import javax.xml.namespace.QName;

import org.apache.cxf.endpoint.Client;
import org.apache.cxf.frontend.ClientProxy;
import org.apache.cxf.transport.http.HTTPConduit;
import org.apache.cxf.transports.http.configuration.HTTPClientPolicy;

/**
 * This class was generated by Apache CXF 3.0.2
 * 2014-12-04T17:57:43.888+08:00
 * Generated source version: 3.0.2
 * 
 */
public final class IMPMsgPubQryService_MPMsgPubQryServiceImplPort_Client {

    private static final QName SERVICE_NAME = new QName("http://impl.mp.uap.yonyou.com/", "iMPMsgPubQryService");

    private IMPMsgPubQryService_MPMsgPubQryServiceImplPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = IMPMsgPubQryService_Service.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        IMPMsgPubQryService_Service ss = new IMPMsgPubQryService_Service(wsdlURL, SERVICE_NAME);
        IMPMsgPubQryService port = ss.getMPMsgPubQryServiceImplPort();  
        Client client = ClientProxy.getClient(port);  
        HTTPConduit http = (HTTPConduit) client.getConduit();  
        HTTPClientPolicy httpClientPolicy = new HTTPClientPolicy();  
        httpClientPolicy.setConnectionTimeout(60*1000);  
        httpClientPolicy.setAllowChunking(false);  
        httpClientPolicy.setReceiveTimeout(60*1000);  
        http.setClient(httpClientPolicy); 
        
        {
//        Date oneweek=new Date(new Date().getTime() -60*60*24*1*1000);
        List<MpMessageUrlVO> messageVOs;
        //messageVOs = hw.getMessageVOsByUserAndSystemAndType("shenjie", "WB", "TASK");
		Date oneweek=new Date(new Date().getTime() -60*60*24*1*1000/24/60);
//		messageVOs = hw.getMessageVOsByUserAndSystemAndType(String.valueOf(oneweek.getTime()),"WB","TASK");
		
//		logger.info(String.valueOf(null!=messageVOs?messageVOs.size():0));
        System.out.println("Invoking getMessageVOsByUserAndSystemAndType...");
        java.lang.String _getMessageVOsByUserAndSystemAndType_arg0 = String.valueOf(oneweek.getTime());
        java.lang.String _getMessageVOsByUserAndSystemAndType_arg1 = "WB";
        java.lang.String _getMessageVOsByUserAndSystemAndType_arg2 = "TASK";
        try {
            java.util.List<com.yonyou.weixin.core.mp.client.MpMessageUrlVO> _getMessageVOsByUserAndSystemAndType__return = port.getMessageVOsByUserAndSystemAndType(_getMessageVOsByUserAndSystemAndType_arg0, _getMessageVOsByUserAndSystemAndType_arg1, _getMessageVOsByUserAndSystemAndType_arg2);
            System.out.println("getMessageVOsByUserAndSystemAndType.result=" + _getMessageVOsByUserAndSystemAndType__return);

        } catch (Exception_Exception e) { 
            System.out.println("Expected exception: Exception has occurred.");
            System.out.println(e.toString());
        }
            }

        System.exit(0);
    }

}
