
package com.yonyou.weixin.core.cxf.client;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 3.0.2
 * 2014-12-01T09:26:40.203+08:00
 * Generated source version: 3.0.2
 * 
 */
 
public class YYUserWS_YYUserWSPort_Server{

    protected YYUserWS_YYUserWSPort_Server() throws java.lang.Exception {
        System.out.println("Starting Server");
        Object implementor = new YYUserWSPortImpl();
        String address = "http://121.42.24.106/note-web/ws/YYUserWS";
        Endpoint.publish(address, implementor);
    }
    
    public static void main(String args[]) throws java.lang.Exception { 
        new YYUserWS_YYUserWSPort_Server();
        System.out.println("Server ready..."); 
        
        Thread.sleep(5 * 60 * 1000); 
        System.out.println("Server exiting");
        System.exit(0);
    }
}
