package com.yonyou.weixin.core.cxf.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.2
 * 2014-12-04T11:00:38.662+08:00
 * Generated source version: 3.0.2
 * 
 */
@WebService(targetNamespace = "http://service.yyuser.cxf.note.dd.org/", name = "YYUserWS")
@XmlSeeAlso({ObjectFactory.class})
public interface YYUserWS {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "bindUser", targetNamespace = "http://service.yyuser.cxf.note.dd.org/", className = "com.yonyou.weixin.core.cxf.client.BindUser")
    @WebMethod
    @ResponseWrapper(localName = "bindUserResponse", targetNamespace = "http://service.yyuser.cxf.note.dd.org/", className = "com.yonyou.weixin.core.cxf.client.BindUserResponse")
    public java.lang.String bindUser(
        @WebParam(name = "userid", targetNamespace = "")
        java.lang.String userid,
        @WebParam(name = "username", targetNamespace = "")
        java.lang.String username,
        @WebParam(name = "password", targetNamespace = "")
        java.lang.String password
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "updateUser", targetNamespace = "http://service.yyuser.cxf.note.dd.org/", className = "com.yonyou.weixin.core.cxf.client.UpdateUser")
    @WebMethod
    @ResponseWrapper(localName = "updateUserResponse", targetNamespace = "http://service.yyuser.cxf.note.dd.org/", className = "com.yonyou.weixin.core.cxf.client.UpdateUserResponse")
    public java.lang.String updateUser(
        @WebParam(name = "userid", targetNamespace = "")
        java.lang.String userid,
        @WebParam(name = "username", targetNamespace = "")
        java.lang.String username,
        @WebParam(name = "password", targetNamespace = "")
        java.lang.String password
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "findUser", targetNamespace = "http://service.yyuser.cxf.note.dd.org/", className = "com.yonyou.weixin.core.cxf.client.FindUser")
    @WebMethod
    @ResponseWrapper(localName = "findUserResponse", targetNamespace = "http://service.yyuser.cxf.note.dd.org/", className = "com.yonyou.weixin.core.cxf.client.FindUserResponse")
    public java.lang.String findUser(
        @WebParam(name = "userid", targetNamespace = "")
        java.lang.String userid
    );
}
