
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.yonyou.weixin.core.cxf.client;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.2
 * 2014-12-04T11:00:38.662+08:00
 * Generated source version: 3.0.2
 * 
 */

@javax.jws.WebService(
                      serviceName = "YYUserWSService",
                      portName = "YYUserWSPort",
                      targetNamespace = "http://service.yyuser.cxf.note.dd.org/",
                      wsdlLocation = "http://121.42.24.106/note-web/ws/YYUserWS?wsdl",
                      endpointInterface = "com.yonyou.weixin.core.cxf.client.YYUserWS")
                      
public class YYUserWSPortImpl implements YYUserWS {

    private static final Logger LOG = Logger.getLogger(YYUserWSPortImpl.class.getName());

    /* (non-Javadoc)
     * @see com.yonyou.weixin.core.cxf.client.YYUserWS#bindUser(java.lang.String  userid ,)java.lang.String  username ,)java.lang.String  password )*
     */
    public java.lang.String bindUser(java.lang.String userid,java.lang.String username,java.lang.String password) { 
        LOG.info("Executing operation bindUser");
        System.out.println(userid);
        System.out.println(username);
        System.out.println(password);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.yonyou.weixin.core.cxf.client.YYUserWS#updateUser(java.lang.String  userid ,)java.lang.String  username ,)java.lang.String  password )*
     */
    public java.lang.String updateUser(java.lang.String userid,java.lang.String username,java.lang.String password) { 
        LOG.info("Executing operation updateUser");
        System.out.println(userid);
        System.out.println(username);
        System.out.println(password);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.yonyou.weixin.core.cxf.client.YYUserWS#findUser(java.lang.String  userid )*
     */
    public java.lang.String findUser(java.lang.String userid) { 
        LOG.info("Executing operation findUser");
        System.out.println(userid);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
